language: php

php:
- 7.3.4

services: 
- docker

sudo: required

before_install:
- sudo service mysql stop
- service --status-all
#- docker-compose up -d
#- docker exec usermanagement_db_1 "service mysql restart"

script:
#- find . -type f -iname "*.php" -print0 | xargs -0 -n1 php -l
#- python tests/user.py
#- python tests/company.py
