language: bash

# php:
# - 7.3.4

dist: trusty

services: 
- docker
- mysql

# sudo: required

before_install:
# - sudo service mysql stop
- service --status-all
# - docker-compose build
- docker-compose up -d

script:
#- find . -type f -iname "*.php" -print0 | xargs -0 -n1 php -l
# - python tests/user.py
- ifconfig
- docker exec usermanagement_db_1 bash -c 'service --status-all'
- sleep 10
- docker exec usermanagement_db_1 bash -c 'service --status-all'
- mysql -h 172.17.0.1 -u root -ptest
#- python tests/company.py
